name: ✅ CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 0'

jobs:
  CI:
    uses: libhal/libhal/.github/workflows/checks.yml@main
    with:
      library: libhal-library
      coverage: true
    secrets: inherit